- id: bonus_room_enterance_light_on_at_sunset
  alias: Bonus Room Enterence Light - Evening On
  description: Turn on Bonus Room Enterence Light at sunset
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state_attr(''sun.sun'', ''elevation'') }}'
    below: 4
  action:
    service: homeassistant.turn_on
    entity_id: switch.bonus_room_enterance_light
- id: salt_lamp_evening_on
  alias: Salt Lamp - Evening On
  description: Turn on Salt Lamp after sunset
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state_attr(''sun.sun'', ''elevation'') }}'
    below: -5.0
  action:
  - service: homeassistant.turn_on
    entity_id: switch.salt_lamp
  - delay: 00:10:00
  - service: light.turn_on
    entity_id: light.kitchen_string_lights
  mode: single
- id: kitchen_light_evening_on
  alias: Kitchen Light - Evening On
  description: Turn on Kitchen Light at sunset
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state_attr(''sun.sun'', ''elevation'') }}'
    below: 4
  action:
    service: homeassistant.turn_on
    entity_id: switch.kitchen_light
- id: salt_lamp_night_off
  alias: Salt Lamp - Night Off
  description: Turn off Salt Lamp at night
  trigger:
    platform: time
    at: '23:59:00'
  action:
    service: homeassistant.turn_off
    entity_id: switch.salt_lamp
- id: kitchen_light_night_off
  alias: Kitchen Light - Night Off
  description: Turn off Kitchen Light at night
  trigger:
    platform: time
    at: '23:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: switch.kitchen_light
- id: day_masterbedroom_light_brightness
  alias: Master Bedroom Light - set daytime brightness to 75
  description: Set Master Bedroom light daytime brightness to 75
  trigger:
    platform: time
    at: '10:00:00'
  action:
  - service: light.turn_on
    target:
      entity_id: light.master_bedroom_light
    data:
      brightness_pct: 75
  - delay: 00:02:00
  - service: light.turn_off
    target:
      entity_id: light.master_bedroom_light
- id: day_masterbedroom_light_brightness_off
  alias: Master Bedroom Light - set daytime brightness to 75 - off
  description: Set Master Bedroom light daytime brightness to 75
  trigger:
    platform: time
    at: '10:01:00'
  action:
  - service: light.turn_off
    target:
      entity_id: light.master_bedroom_light
- id: plant_lights_morning_on
  alias: Plant Lights - Morning On
  description: Turn on the plant lights around sun rise
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state_attr(''sun.sun'', ''elevation'') }}'
    above: 5.0
  action:
  - service: homeassistant.turn_on
    entity_id: switch.plant_room
  - delay: 00:00:30
  - service: homeassistant.turn_on
    entity_id: switch.plant_light_1
  - delay: 00:00:30
  - service: homeassistant.turn_on
    entity_id: swith.plant_light_2
- id: plant_lights_evening_off
  alias: Plant Lights - Evening Off
  description: Turn off the plant lights around sun set
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state_attr(''sun.sun'', ''elevation'') }}'
    below: -5.0
  action:
  - service: homeassistant.turn_off
    entity_id: switch.plant_room
  - delay: 00:00:30
  - service: homeassistant.turn_off
    entity_id: switch.plant_light_1
  - delay: 00:00:30
  - service: homeassistant.turn_off
    entity_id: swith.plant_light_2
- id: ariving_home_turn_on_external_lights
  alias: Ariving home, turn on external lights
  description: Someone is ariving home, turn on the external lights for 6 minutes.
  trigger:
    platform: state
    entity_id:
    - person.StyxUT
    - person.traci
    - person.samantha
  condition:
  - condition: template
    value_template: '{{ trigger.from_state.state != trigger.to_state.state }}'
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  - condition: state
    entity_id: switch.external_lights
    state: 'off'
  action:
  - delay: 00:01:00
  - service: homeassistant.turn_on
    entity_id: switch.external_lights
  - delay: 00:06:00
  - service: homeassistant.turn_off
    entity_id: switch.external_lights
- id: bug_zapper_evening_on
  alias: Bug Zapper - Evening On
  description: Turn on bug zapper after sunset
  trigger:
    platform: sun
    event: sunset
    offset: -00:30:00
  action:
  - service: homeassistant.turn_on
    entity_id: switch.dual_outlet_one
- id: bug_zapper_morning_off
  alias: Bug Zapper - Morning off
  description: Turn off bug zapper before sunrise
  trigger:
    platform: sun
    event: sunrise
    offset: -02:00:00
  action:
  - service: homeassistant.turn_off
    entity_id: switch.dual_outlet_one
- id: external_lights_dark_on
  alias: External Lights - Evening On
  description: Turn on External Lights at dark
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state_attr(''sun.sun'', ''elevation'') }}'
    below: -4.0
  action:
    service: homeassistant.turn_on
    entity_id: switch.external_lights
- id: external_lights_night_off
  alias: Externals Light - Night Off
  description: Turn off External Lights at midnight
  trigger:
    platform: time
    at: '23:59:00'
  action:
    service: homeassistant.turn_off
    entity_id: switch.external_lights
- id: garage_door_delayed_off
  alias: Back Garage Door - Delayed Off
  description: Turn off Garage Door after two hours
  trigger:
    platform: state
    to: 'on'
    entity_id: switch.garage_door
  action:
  - service: homeassistant.turn_on
    entity_id: switch.garage_door
  - delay: 02:00:00
  - service: homeassistant.turn_off
    entity_id: switch.garage_door
- id: notify_person_is_ariving_home
  alias: Notify when someone enters the Home Area
  description: Send a notification when someone enters the Home Area
  trigger:
  - platform: zone
    entity_id:
    - person.traci
    - person.styxut
    - person.samantha
    zone: zone.home_area
    event: enter
  action:
  - service: "{% if trigger.from_state.attributes.friendly_name == 'Traci' %}\n  notify.styx_devices\n{%
      else %}\n  notify.home_resident_devices\n{% endif %}\n"
    data:
      title: '"{{ trigger.to_state.attributes.friendly_name }} is Arriving Home"

        '
      message: '"{{ trigger.to_state.attributes.friendly_name }} is arriving home."

        '
  mode: single
- id: notify_on_UPS_status_change
  alias: Notify that UPS status has changed
  description: Notify when the UPS status has changed
  trigger:
  - platform: state
    entity_id: sensor.ups_status
  action:
  - service: notify.home_resident_devices
    data:
      title: UPS Status Changed
      message: '"UPS status has changed from ''{{ trigger.from_state.state }}'' to
        ''{{ trigger.to_state.state }}''. Verify that the server is fully powered
        on."

        '
  mode: single
- id: notify_traci_leaves_work
  alias: Notify when Traci leaves work for the day
  description: Send notification when Traci leaves work for the day
  trigger:
  - platform: zone
    entity_id:
    - person.traci
    zone: zone.traci_work
    event: leave
  action:
  - service: notify.styx_devices
    data:
      title: '"{{ trigger.to_state.attributes.friendly_name }} Leaving Work"

        '
      message: '"{{ trigger.to_state.attributes.friendly_name }} has left work for
        the day."

        '
  mode: single
- id: notify_leaving_arena_car_conditioning_started
  alias: Notify when leaving arena that car conditioning has started
  description: Send a notification that car conditioning has started
  trigger:
  - platform: zone
    entity_id:
    - person.styxut
    zone: zone.arena
    event: leave
  condition:
  - condition: zone
    entity_id: device_tracker.charon_location_tracker
    zone: zone.station_parking
  action:
  - service: homeassistant.turn_on
    entity_id: climate.charon_hvac_climate_system
  - service: notify.styx_devices
    data:
      title: 'Reminder: Condition Car'
      message: Remember to condition the car upon leaving the arena.
  mode: single
- id: notify_charon_charging_stopped
  alias: Notify driver that charging of Charon has been stopped by HomeAssistant
  description: Notify driver that charging of Charon has been stopped by HomeAssistant
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.tesla_wall_connector_south_vehicle_connected
    from: 'off'
    to: 'on'
  action:
  - service: homeassistant.turn_off
    entity_id: switch.charon_charger
  - service: notify.styx_devices
    data:
      title: Charon - Charging Stopped
      message: Charon - Charging has been stopped by HomeAssistant
  mode: single
- id: enable_power_for_riolink_e1_pro_cameras
  alias: Enable power for RioLink E1 Pro cameras
  description: turn on power to camaras when no one is home
  trigger:
    platform: state
    entity_id: person.traci, person.styxut, person.samantha
    to: not_home
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: person.traci
      state: not_home
    - condition: state
      entity_id: person.styxut
      state: not_home
    - condition: state
      entity_id: person.samantha
      state: not_home
  action:
  - service: switch.turn_on
    entity_id: switch.riolink_e1_pro_1
  - service: switch.turn_on
    entity_id: switch.riolink_e1_pro_2
  mode: single
- id: disable_power_for_riolink_e1_pro_cameras
  alias: Disable power for RioLink E1 Pro cameras
  description: turn off power to cameras when anyone is home
  trigger:
    platform: state
    entity_id: person.traci, person.styxut, person.samantha
    to: home
  action:
  - service: switch.turn_off
    entity_id: switch.riolink_e1_pro_1
  - service: switch.turn_off
    entity_id: switch.riolink_e1_pro_2
  mode: single
- id: backyard_motion_detected
  alias: Backyard motion detected, turn on deck light
  trigger:
    type: motion
    platform: device
    device_id: cf9665957192c22e906246f838576b83
    entity_id: binary_sensor.backyard_4
    domain: binary_sensor
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - service: homeassistant.turn_on
    entity_id: switch.deck_light
  - delay: 00:06:00
  - service: homeassistant.turn_off
    entity_id: switch.deck_light
  - delay: 00:00:05
  mode: restart
- id: front_yard_motion_detected
  alias: Front yard motion detected, turn on external lights
  trigger:
  - type: motion
    platform: device
    device_id: 6c1b836e5eb3097d0614f453634ecd6b
    entity_id: 225fbe9c304959c91e1dd7e027080ab7
    domain: binary_sensor
  condition:
  - and:
    - condition: time
      after: 00:02:00
    - condition: sun
      before: sunrise
  action:
  - service: homeassistant.turn_on
    entity_id: switch.external_lights
  - delay:
      hours: 0
      minutes: 20
      seconds: 0
      milliseconds: 0
  - service: homeassistant.turn_off
    entity_id: switch.external_lights
  - delay: 00:00:05
  mode: single
- id: thermostat_night_temperature
  alias: Thermostat - set nighttime temperature range
  description: Set the thermostat the nighttime temperature range
  trigger:
  - platform: time
    at: 00:01:00
  action:
  - service: climate.set_temperature
    data:
      target_temp_high: 78
      target_temp_low: 56
      hvac_mode: heat_cool
    target:
      entity_id: climate.hallway_thermostat_2
  mode: single
- id: thermostat_day_temperature
  alias: Thermostat - set daytime temperature range
  description: Set the thermostat the daytime temperature range
  trigger:
  - platform: time
    at: '12:01:00'
  action:
  - service: climate.set_temperature
    data:
      target_temp_high: 74
      target_temp_low: 65
      hvac_mode: heat_cool
    target:
      entity_id: climate.hallway_thermostat_2
  mode: single
- id: thermostat_evening_temperature
  alias: Thermostat - set evening temperature range
  description: Set the thermostat the evening temperature range
  trigger:
  - platform: time
    at: '15:00:00'
  action:
  - service: climate.set_temperature
    data:
      target_temp_high: 77
      target_temp_low: 64
      hvac_mode: heat_cool
    target:
      entity_id: climate.hallway_thermostat_2
  mode: single
- id: shellies_announce
  alias: Shellies Announce
  trigger:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    minutes: /30
  action:
    service: mqtt.publish
    data:
      topic: shellies/command
      payload: announce
  mode: single
- id: shellies_discovery
  alias: Shellies Discovery
  mode: queued
  max: 999
  trigger:
    platform: mqtt
    topic: shellies/announce
  action:
    service: python_script.shellies_discovery
    data:
      id: '{{ trigger.payload_json.id }}'
      mac: '{{ trigger.payload_json.mac }}'
      fw_ver: '{{ trigger.payload_json.fw_ver }}'
      model: '{{ trigger.payload_json.model }}'
      mode: '{{ trigger.payload_json.mode | default }}'
