#########################################################################
###  Light Control
#########################################################################
- id: bonus_room_enterance_light_on_at_sunset
  alias: Bonus Room Enterence Light - Evening On
  description: Turn on Bonus Room Enterence Light at sunset
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state_attr('sun.sun', 'elevation') }}"
    below: 3.5
  action:
    service: homeassistant.turn_on
    entity_id: switch.bonus_room_enterance_light
- id: salt_lamp_evening_on
  alias: Salt Lamp - Evening On
  description: Turn on Salt Lamp after sunset
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state_attr('sun.sun', 'elevation') }}"
    below: -5.0
  action:
  - service: homeassistant.turn_on
    entity_id: switch.salt_lamp
  mode: single
- id: kitchen_light_evening_on
  alias: Kitchen Light - Evening On
  description: Turn on Kitchen Light at sunset
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state_attr('sun.sun', 'elevation') }}"
    below: 3.5
  action:
    service: homeassistant.turn_on
    entity_id: switch.kitchen_light
- id: plant_light_morning_on
  alias: Plant Light - Morning On
  description: Turn on Plant Light after sunrise
  trigger:
    platform: sun
    event: sunrise
    offset: 00:30:00
  action:
    service: homeassistant.turn_on
    entity_id: switch.plant_light
- id: plant_light_evening_off
  alias: plant Light - Evening Off
  description: Turn off Plant Light before sunset
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state_attr('sun.sun', 'elevation') }}"
    below: -6.0
  action:
    service: homeassistant.turn_off
    entity_id: switch.plant_light
- id: salt_lamp_night_off
  alias: Salt Lamp - Night Off
  description: Turn off Salt Lamp at night
  trigger:
    platform: time
    at: '23:59:00'
  action:
    service: homeassistant.turn_off
    entity_id: switch.salt_lamp
- id: kitchen_light_night_off
  alias: Kitchen Light - Night Off
  description: Turn off Kitchen Light at night
  trigger:
    platform: time
    at: '23:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: switch.kitchen_light
- id: external_lights_dark_on
  alias: External Lights - Evening On
  description: Turn on External Lights at dark
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state_attr('sun.sun', 'elevation') }}"
    below: -4.0
  action:
    service: homeassistant.turn_on
    entity_id: switch.external_lights
- id: external_lights_night_off
  alias: External Light - Night Off
  description: Turn off External Lights at midnight
  trigger:
    platform: time
    at: '23:59:00'
  action:
    service: homeassistant.turn_off
    entity_id: switch.external_lights
- id: garage_door_delayed_off
  alias: Back Garage Door - Delayed Off
  description: Turn off Garage Door after two hours
  trigger:
    platform: state
    to: 'on'
    entity_id: switch.garage_door
  action:
  - service: homeassistant.turn_on
    entity_id: switch.garage_door
  - delay: 02:00:00
  - service: homeassistant.turn_off
    entity_id: switch.garage_door
- id: ariving_home_turn_on_external_lights
  alias: Ariving home, turn on external lights
  description: Someone is ariving home, turn on the external lights for 10 minutes.
  trigger:
    platform: state
    entity_id: 
      - person.StyxUT
      - person.traci
      - person.samantha
  condition:
  - condition: template
    value_template: '{{ trigger.from_state.state != trigger.to_state.state }}'
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  - condition: state
    entity_id: switch.external_lights
    state: 'off'
  action:
  - service: homeassistant.turn_on
    entity_id: switch.external_lights
  - delay: 00:10:00
  - service: homeassistant.turn_off
    entity_id: switch.external_lights

#########################################################################
###  Notifications
#########################################################################
#https://community.home-assistant.io/t/automation-for-entering-and-leaving-zones/265000/3
- id: notify_person_is_ariving_home
  alias: Notify when someone enters the Home Area
  description: Send a notification when someone enters the Home Area
  trigger:
    - platform: zone
      entity_id:
         - person.traci
         - person.styxut
         - person.samantha
      zone: zone.home_area
      event: enter
  action:
    - service: >
        {% if trigger.from_state.attributes.friendly_name == 'Traci' %}
          notify.styx_devices
        {% else %}
          notify.home_resident_devices
        {% endif %}
      data:
        title: >
          {{ trigger.to_state.attributes.friendly_name }} is Arriving Home
        message: >
          {{ trigger.to_state.attributes.friendly_name }} is arriving home.
  mode: single

#########################################################################
###  Night Motion Detection
#########################################################################
- id: backyard_motion_detected
  alias: Backyard motion detected, turn on deck light
  trigger:
  # - platform: event
  #   event_type: nest_event
  #   event_data:
  #     device_id: camera.backyard
  #     type: camera_motion
    - platform: device
      device_id: 28319699b614915a42f1c29b1c6305fd
      domain: nest
      type: camera_motion # available options are: camera_person, camera_sound, camera_motion
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  # - condition: state
  #   entity_id: switch.deck_light
  #   state: 'off'
  action:
  - service: homeassistant.turn_on
    entity_id: switch.deck_light
  - delay: 00:03:00
  - service: homeassistant.turn_off
    entity_id: switch.deck_light
  mode: restart

#########################################################################
###  Tasmotas
#########################################################################
# - id: tasmotas_announce
#   alias: Tasmotas Announce
#   description: 'Prevents devices from going Unavailable'
#   trigger:
#     - platform: Home Assistant
#       event: start
#     - platform: time_pattern
#       hours: /1
#   condition: []
#   action:
#     # For reasons that I don't understand, different tasmota devices seem to 
#     #     subscribe to a different group topic. cmnd/tas vs tas/cmnd
#     ##
#     - service: mqtt.publish
#       data:
#         topic: cmnd/tasmotas/SetOption19
#         payload: '0'
#     - service: mqtt.publish
#       data:
#         topic: tasmotas/cmnd/SetOption19
#         payload: '0'
#   mode: single

#########################################################################
###  Temperature Control
#########################################################################
- id: thermostat_afternoon_run_fan
  alias: Thermostat - run fan in afternoon
  description: Run the fan for 10 minutes at 3:45 PM
  trigger:
  - platform: time
    at: '15:45:00'
  condition: "{{ ((states('sensor.shelly_h_t_ac7dca_temperature') | float) - (states('sensor.hallway_temperature') | float)) | abs <= 5 }}" # basement shelly
  action:
  - service: climate.set_fan_mode
    data:
      entity_id: climate.hallway
      fan_mode: 'on'
  - delay: 00:10:00
  - service: climate.set_fan_mode
    data:
      entity_id: climate.hallway
      fan_mode: 'off'
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.hallway
      hvac_mode: heat_cool
- id: thermostat_afternoon_run_fan_2
  alias: Thermostat - run fan in late afternoon
  description: Run the fan for 10 minutes at 4:30 PM
  trigger:
  - platform: time
    at: '16:30:00'
  condition: "{{ ((states('sensor.shelly_h_t_ac7dca_temperature') | float) - (states('sensor.hallway_temperature') | float)) | abs >= 4 }}" # basement shelly
  action:
    - service: homeassistant.turn_on
      entity_id: switch.desk_power
    - service: climate.set_fan_mode
      data:
        entity_id: climate.hallway
        fan_mode: 'on'
    - delay: 00:10:00
    - service: climate.set_fan_mode
      data:
        entity_id: climate.hallway
        fan_mode: 'off'
    - service: climate.set_hvac_mode
      data:
        entity_id: climate.hallway
        hvac_mode: heat_cool
  mode: single
- id: thermostat_night_temperature
  alias: Thermostat - set nighttime temperature range
  description: Set the thermostat the nighttime temperature range
  trigger:
  - platform: time
    at: 00:05:00
  action:
  - service: climate.set_temperature
    data:
      entity_id: climate.hallway
      target_temp_high: 77
      target_temp_low: 55
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.hallway
      hvac_mode: heat_cool
  mode: single
- id: thermostat_day_temperature
  alias: Thermostat - set daytime temperature range
  description: Set the thermostat the daytime temperature range
  trigger:
  - platform: time
    at: 07:30:00
  action:
  - service: climate.set_temperature
    data:
      entity_id: climate.hallway
      target_temp_high: 77
      target_temp_low: 64
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.hallway
      hvac_mode: heat_cool

#########################################################################
###  Shelly
#########################################################################
- id: shellies_announce
  alias: 'Shellies Announce'
  trigger:
    - platform: homeassistant
      event: start
    - platform: time_pattern
      hours: "/1"  # Modifying this if you are using Shelly Motion can drain your device's battery quickly.
  action:
    service: mqtt.publish
    data:
      topic: shellies/command
      payload: announce
  mode: single
- id: shellies_discovery
  alias: 'Shellies Discovery'
  mode: queued
  max: 999
  trigger:
    platform: mqtt
    topic: shellies/announce
  action:
    service: python_script.shellies_discovery
    data:
      id: '{{ trigger.payload_json.id }}'
      mac: '{{ trigger.payload_json.mac }}'
      fw_ver: '{{ trigger.payload_json.fw_ver }}'
      model: '{{ trigger.payload_json.model }}'
      mode: '{{ trigger.payload_json.mode | default }}'


# - id: aaa_test_automation
#   alias: aaa_test_automation
#   description: aaa_test_automation
#   trigger:
#   - platform: state
#     entity_id: switch.bonus_room_enterance_light
#     to: 'on'
#   condition: "{{ ((states('sensor.shelly_h_t_ac7dca_temperature') | float) - (states('sensor.hallway_temperature') | float)) | abs <= 5 }}"
#   # "{{ states('sensor.shelly_h_t_ac7dca_temperature') | float < 100 }}" #<-  works
#   # "{{ states('sensor.hallway_temperature') | float < 100 }}" #<-  works
#   action:
#     - service: homeassistant.turn_on
#       entity_id: switch.desk_power
#   mode: single