#########################################################################
###  Light Control
#########################################################################
- id: bonus_room_enterance_light_on_at_sunset
  alias: Bonus Room Enterence Light - Evening On
  description: Turn on Bonus Room Enterence Light at sunset
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state_attr('sun.sun', 'elevation') }}"
    below: 4
  action:
    service: homeassistant.turn_on
    entity_id: switch.bonus_room_enterance_light
- id: salt_lamp_evening_on
  alias: Salt Lamp - Evening On
  description: Turn on Salt Lamp after sunset
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state_attr('sun.sun', 'elevation') }}"
    below: -5.0
  action:
  - service: homeassistant.turn_on
    entity_id: switch.salt_lamp
  mode: single
- id: kitchen_light_evening_on
  alias: Kitchen Light - Evening On
  description: Turn on Kitchen Light at sunset
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state_attr('sun.sun', 'elevation') }}"
    below: 4
  action:
    service: homeassistant.turn_on
    entity_id: switch.kitchen_light
- id: salt_lamp_night_off
  alias: Salt Lamp - Night Off
  description: Turn off Salt Lamp at night
  trigger:
    platform: time
    at: '23:59:00'
  action:
    service: homeassistant.turn_off
    entity_id: switch.salt_lamp
- id: kitchen_light_night_off
  alias: Kitchen Light - Night Off
  description: Turn off Kitchen Light at night
  trigger:
    platform: time
    at: '23:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: switch.kitchen_light
- id: day_masterbedroom_light_brightness
  alias: Master Bedroom Light - set daytime brightness to 100
  description: Set Master Bedroom light daytime brightness to 100
  trigger:
    platform: time
    at: '12:00:00'
  action:
  - service: homeassistant.turn_off
    data: { brightness: 100 }
    target:
      entity_id:
        - light.master_bedroom_light

##########################################################    
# enable after holiday season
##########################################################
# - id: external_lights_dark_on
#   alias: External Lights - Evening On
#   description: Turn on External Lights at dark
#   trigger:
#   - platform: numeric_state
#     entity_id: sun.sun
#     value_template: "{{ state_attr('sun.sun', 'elevation') }}"
#     below: -4.0
#   action:
#     service: homeassistant.turn_on
#     entity_id: switch.external_lights
# - id: external_lights_night_off
#   alias: Externals Light - Night Off
#   description: Turn off External Lights at midnight
#   trigger:
#     platform: time
#     at: '23:59:00'
#   action:
#     service: homeassistant.turn_off
#     entity_id: switch.external_lights
# - id: plant_light_morning_on
#   alias: Plant Light - Morning On
#   description: Turn on Plant Light before sunrise
#   trigger:
#     platform: sun
#     event: sunrise
#     offset: -00:30:00
#   action:
#     - service: homeassistant.turn_on
#       entity_id: switch.plant_light_02
#     - service: homeassistant.turn_on
#       entity_id: switch.plant_light_01
# - id: plant_light_evening_off
#   alias: Plant Light - Evening Off
#   description: Turn off Plant Light at sunset
#   trigger:
#   - platform: numeric_state
#     entity_id: sun.sun
#     value_template: "{{ state_attr('sun.sun', 'elevation') }}"
#     below: -6.0
#   action:
#     - service: homeassistant.turn_off
#       entity_id: switch.plant_light_01
#     - service: homeassistant.turn_off
#       entity_id: switch.plant_light_02
########################################################## -- end enable

##########################################################    
# disable after holiday season
##########################################################
- id: holiday_lights_dark_on
  alias: Holiday Lights - Evening On
  description: Turn on Holiday Lights at dark
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state_attr('sun.sun', 'elevation') }}"
    below: -4.0
  action:
    - service: homeassistant.turn_on
      entity_id: switch.front_eaves
    - service: homeassistant.turn_on
      entity_id: switch.plant_light_01 # outside x-mas light
- id: holiday_lights_night_off
  alias: Holiday Lights - Night Off
  description: Turn off Holiday Lights at midnight
  trigger:
    platform: time
    at: '02:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: switch.front_eaves
- id: plant_light_morning_on
  alias: Plant Light - Morning On
  description: Turn on Plant Light before sunrise
  trigger:
    platform: sun
    event: sunrise
    offset: -00:30:00
  action:
    - service: homeassistant.turn_on
      entity_id: switch.plant_light_02
    - service: homeassistant.turn_on
      entity_id: switch.dual_outlet_one # plant light
    - service: homeassistant.turn_on
      entity_id: switch.dual_outlet_two # inside x-mas lights
- id: plant_light_evening_off
  alias: Plant Light - Evening Off
  description: Turn off Plant Light at sunset
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state_attr('sun.sun', 'elevation') }}"
    below: -6.0
  action:
    - service: homeassistant.turn_off
      entity_id: switch.plant_light_02
    - service: homeassistant.turn_off
      entity_id: switch.dual_outlet_one # plant light
########################################################## -- end disable
- id: garage_door_delayed_off
  alias: Back Garage Door - Delayed Off
  description: Turn off Garage Door after two hours
  trigger:
    platform: state
    to: 'on'
    entity_id: switch.garage_door
  action:
  - service: homeassistant.turn_on
    entity_id: switch.garage_door
  - delay: 02:00:00
  - service: homeassistant.turn_off
    entity_id: switch.garage_door

- id: ariving_home_turn_on_external_lights
  alias: Ariving home, turn on external lights
  description: Someone is ariving home, turn on the external lights for 6 minutes.
  trigger:
    platform: state
    entity_id: 
      - person.StyxUT
      - person.traci
      - person.samantha
  condition:
  - condition: template
    value_template: '{{ trigger.from_state.state != trigger.to_state.state }}'
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  - condition: state
    entity_id: switch.external_lights
    state: 'off'
  action:
  - delay: 00:01:00
  - service: homeassistant.turn_on
    entity_id: switch.external_lights
  - delay: 00:06:00
  - service: homeassistant.turn_off
    entity_id: switch.external_lights

#########################################################################
###  Notifications
#########################################################################
#https://community.home-assistant.io/t/automation-for-entering-and-leaving-zones/265000/3
- id: notify_person_is_ariving_home
  alias: Notify when someone enters the Home Area
  description: Send a notification when someone enters the Home Area
  trigger:
    - platform: zone
      entity_id:
         - person.traci
         - person.styxut
         - person.samantha
      zone: zone.home_area
      event: enter
  action:
    - service: >
        {% if trigger.from_state.attributes.friendly_name == 'Traci' %}
          notify.styx_devices
        {% else %}
          notify.home_resident_devices
        {% endif %}
      data:
        title: >
          "{{ trigger.to_state.attributes.friendly_name }} is Arriving Home"
        message: >
          "{{ trigger.to_state.attributes.friendly_name }} is arriving home."
  mode: single

- id: notify_on_UPS_status_change
  alias: Notify that UPS status has changed
  description: Notify when the UPS status has changed
  trigger:
  - platform: state
    entity_id: sensor.ups_status
  action:
  - service: notify.home_resident_devices
    data:
      title: 'UPS Status Changed'
      message: >
        "UPS status has changed from '{{ trigger.from_state.state }}' to '{{ trigger.to_state.state }}'.
        Verify that the server is fully powered on."
  mode: single

- id: notify_traci_leaves_work
  alias: Notify when Traci leaves work for the day
  description: Send notification when Traci leaves work for the day
  trigger:
    - platform: zone
      entity_id:
      - person.traci
      zone: zone.traci_work
      event: enter
  condition:
  - condition: time
    after: '14:00:00'
    before: '22:00:00'
  action:
  - service: >
      notify.styx_devices
    data:
      title: >
        "{{ trigger.to_state.attributes.friendly_name }} has left work"
      message: >
        "{{ trigger.to_state.attributes.friendly_name }} has left work."
  mode: single

#########################################################################
###  Night Motion Detection
#########################################################################
- id: backyard_motion_detected
  alias: Backyard motion detected, turn on deck light
  trigger:
    type: motion
    platform: device
    device_id: cf9665957192c22e906246f838576b83
    entity_id: binary_sensor.backyard_4
    domain: binary_sensor
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - service: homeassistant.turn_on
    entity_id: switch.deck_light
  - delay: 00:03:00
  - service: homeassistant.turn_off
    entity_id: switch.deck_light
  - delay: 00:01:00
  mode: single

#########################################################################
###  Temperature Control
#########################################################################
- id: thermostat_afternoon_run_fan
  alias: Thermostat - run fan in afternoon
  description: Run the fan for 10 minutes at 3:45 PM
  trigger:
  - platform: time
    at: '15:45:00'
  condition: "{{ ((states('sensor.shelly_h_t_ac7dca_temperature') | float) - (states('sensor.hallway_temperature') | float)) | abs >= 4 }}" # basement Shelly H&T 
  action:
    - service: climate.set_hvac_mode
      target:
        entity_id: climate.hallway_thermostat
      data:
        hvac_mode: 'off'
    - service: climate.set_fan_mode
      target:
        entity_id: climate.hallway_thermostat
      data:
        fan_mode: 'on'
    - delay: 00:10:00
    - service: climate.set_fan_mode
      target:
        entity_id: climate.hallway_thermostat
      data:
        fan_mode: 'on'
    - service: climate.set_hvac_mode
      target:
        entity_id: climate.hallway_thermostat
      data:
        hvac_mode: heat_cool
  mode: single
- id: thermostat_afternoon_run_fan_2
  alias: Thermostat - run fan in late afternoon
  description: Run the fan for 10 minutes at 4:30 PM
  trigger:
  - platform: time
    at: '16:30:00'
  condition: "{{ ((states('sensor.shelly_h_t_ac7dca_temperature') | float) - (states('sensor.hallway_temperature') | float)) | abs >= 4 }}" # basement shelly H&T
  action:
    - service: climate.set_hvac_mode
      target:
        entity_id: climate.hallway_thermostat
      data:
        hvac_mode: 'off'
    - service: climate.set_fan_mode
      target:
        entity_id: climate.hallway_thermostat
      data:
        fan_mode: 'on'
    - delay: 00:10:00
    - service: climate.set_fan_mode
      target:
        entity_id: climate.hallway_thermostat
      data:
        fan_mode: 'on'
    - service: climate.set_hvac_mode
      target:
        entity_id: climate.hallway_thermostat
      data:
        hvac_mode: heat_cool
  mode: single

- id: thermostat_night_temperature
  alias: Thermostat - set nighttime temperature range
  description: Set the thermostat the nighttime temperature range
  trigger:
  - platform: time
    at: "00:01:00"
  action:
    - service: climate.set_temperature
      data:
        target_temp_high: 76
        target_temp_low: 59
        hvac_mode: heat_cool
      target:
        entity_id: climate.hallway_thermostat
  mode: single
- id: thermostat_day_temperature
  alias: Thermostat - set daytime temperature range
  description: Set the thermostat the daytime temperature range
  trigger:
  - platform: time
    at: "00:05:30"
  action:
    - service: climate.set_temperature
      data:
        target_temp_high: 76
        target_temp_low: 65
        hvac_mode: heat_cool
      target:
        entity_id: climate.hallway_thermostat
  mode: single
#########################################################################
###  Shelly
#########################################################################
- id: shellies_announce
  alias: 'Shellies Announce'
  trigger:
    - platform: homeassistant
      event: start
    - platform: time_pattern
      minutes: "/30"  # Modifying this if you are using Shelly Motion can drain your device's battery quickly.
  action:
    service: mqtt.publish
    data:
      topic: shellies/command
      payload: announce
  mode: single
- id: shellies_discovery
  alias: 'Shellies Discovery'
  mode: queued
  max: 999
  trigger:
    platform: mqtt
    topic: shellies/announce
  action:
    service: python_script.shellies_discovery
    data:
      id: '{{ trigger.payload_json.id }}'
      mac: '{{ trigger.payload_json.mac }}'
      fw_ver: '{{ trigger.payload_json.fw_ver }}'
      model: '{{ trigger.payload_json.model }}'
      mode: '{{ trigger.payload_json.mode | default }}'

# - id: aaa_test_automation
#   alias: aaa_test_automation
#   description: aaa_test_automation
#   trigger:
#   - platform: state
#     entity_id: switch.bonus_room_enterance_light
#     to: 'on'
#   condition: "{{ ((states('sensor.shelly_h_t_ac7dca_temperature') | float) - (states('sensor.hallway_temperature') | float)) | abs <= 5 }}"
#   # "{{ states('sensor.shelly_h_t_ac7dca_temperature') | float < 100 }}" #<-  works
#   # "{{ states('sensor.hallway_temperature') | float < 100 }}" #<-  works
#   action:
#     - service: homeassistant.turn_on
#       entity_id: switch.desk_power
#   mode: single