homeassistant:
  name: Home
  elevation: 1302
  time_zone: America/Denver
  unit_system: imperial
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  internal_url: "http://homeassistant.home:8123"
  external_url: !secret external_url

  auth_providers:
  - type: homeassistant

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

sun:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  #Existed Originally ->> http-request set-header X-Forwarded-Port %[dst_port] ----from HA Proxy Backend pass through
  #       http-request set-header X-Client-IP %[src]
  #       http-request add-header X-Forwarded-Proto https if { ssl_fc }
  #testing ->> http-request replace-value x-forwarded-for ^ "%[hdr(x-forwarded-for)], %[src]"
  use_x_forwarded_for: true
  trusted_proxies:    
    - 192.168.0.0/24
    - 127.0.0.1
    - 192.168.0.211
    - 192.168.0.221
    - 192.168.0.222

  ip_ban_enabled: true
  login_attempts_threshold: 10

python_script:

# MQTT - mosquitto
mqtt:
  broker: k3s-mgmt-001.home
  client_id: home-assistant
  discovery: true
  discovery_prefix: homeassistant

# Text to speech
tts:
  - platform: google_translate

homekit:

neato:
  client_id: !secret neato_client_id
  client_secret: !secret neato_client_secret

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  # "Project ID" in the Device Access Console
  project_id: !secret nest_project_id
  # Provide the full path exactly as shown under "Subscription name" in Google Cloud Console
  subscriber_id: !secret nest_subscriber_id

shelly:

# synology_dsm:
#   host: !secret synology_dsm_host
#   username: !secret synology_dsm_login
#   password: !secret synology_dsm_password
#   ssl: true
#   port: 5001

tplink:
  discovery: true
  switch:
    - host: !secret vr_main
    - host: !secret vr_sensor_1
    - host: !secret vr_sensor_2
    - host: !secret external_lights
    - host: !secret bonus_room_entrance_light
    - host: !secret deck_light
    #- host: !secret external_dual_outlet

wemo:
  discovery: true
  static:
    # lights
    - !secret kitchen_light
    # larger plugs
    - !secret garage_door
    - !secret master_bedroom_lamp
    - !secret salt_lamp
    # smaller plugs
    - !secret plant_light
    - !secret lawn_mower_north
    - !secret desk_power

#group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
zone: !include zones.yaml

# iOS action buttons
ios:
  actions:
  - name: "Let's Go To Bed"
    background_color: "#000000"
    label:
      text: "Let's Go To Bed."
      color: "#33adff"
    icon:
      icon: hass:weather-night
      color: "#951ad3"
# actions:
  - name: "Turn On VR"
    background_color: "#000000"
    label:
      text: "Turn on VR."
      color: "#33adff"
    icon:
      icon: mdi:VirtualReality 
      color: "#951ad3"
#  actions:
  - name: "Turn Off VR"
    background_color: "#000000"
    label:
      text: "Turn off VR."
      color: "#33adff"
    icon:
      icon: mdi:VirtualReality 
      color: "#951ad3"


